### ISSUE TITLE
Protocol error message when starting new relic infra agent with the nri-winservices plugin

### ISSUE THREAD

**Issue by poohbear80** [newrelic/nri-winservices#44]
## Description
I followed the description in the https://docs.newrelic.com/docs/windows-services-integration#install
Installed New Relic agent 1.12.4 on a Windows Server 2012R2

## Expected Behavior
Agent should collect metrics from windows services

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
None

## Steps to Reproduce
Install New Relic agent 1.12.4 on a Windows Server 2012R2
[nri.log](https://github.com/newrelic/nri-winservices/files/5251993/nri.log)

## Your Environment
Windows Server 2012R2
New Relic infra 1.12.4

**Comment by paologallinaharbur** [comment]
Hello @poohbear80, [as mentioned by the docs](https://docs.newrelic.com/docs/windows-services-integration) you need to be added to the beta program in order to be able to actually send data. 

>Thank you for participating in the Windows services integration beta program. We'd appreciate your feedback. To join the beta program, and for comments or questions, [contact us](jjoly@newrelic.com).

This is needed since the integration is using a new protocol that is not enabled for everyone, this is the reason why in the logs you shared you can find the following: `can't parse v4 integration output`

**Comment by poohbear80** [comment]
oh, sorry i missed out that one.
does this protocol enablement affect the other newrelic-infra metrics?

**Comment by paologallinaharbur** [comment]
No, the other integration will carry on using the SDKv3 "protocol" and will be not affected

**Comment by poohbear80** [comment]
ok, thanks, I've requested to join the beta program
